### ISSUE TITLE
React Typescript application this.anything not working

### ISSUE THREAD

**Issue by joeygaitan** [proyecto26/ion-phaser#11]
I fixed the interface in the IonPhaser.d.ts file. The interface was missing game so it would through that error. Now I cant seem to fix this.cameras not showing up in the scene part in the state

```
scene: {
init: function(){
    this.cameras.main.setBackgroundColor('#24252A')
}
```

Neither does anything that is typed with this. Love to be able to get this working. Love the great work you have already put out thanks!

**Comment by jdnichollsc** [comment]
Please attach the repo of your project :)

**Comment by joeygaitan** [comment]
https://github.com/Calcumon/CalcumonFrontend/blob/gameRepo/src/components/levels/level1/index.tsx

**Comment by jdnichollsc** [comment]
@joeygaitan what if you use `game: Phaser.Game` instead of `game: object` here => https://github.com/Calcumon/CalcumonFrontend/blob/gameRepo/src/components/levels/level1/index.tsx#L12
Let me know :)
