### ISSUE TITLE
No overload matches

### ISSUE THREAD

**Issue by LuchitoDev** [proyecto26/ion-phaser#14]
<img width="1270" alt="Captura de Pantalla 2020-03-03 a la(s) 9 20 19 p  m" src="https://user-images.githubusercontent.com/19392344/75842055-f4185600-5d94-11ea-8f78-9c61106c188f.png">

```
import { IonContent, IonHeader, IonPage, IonTitle, IonToolbar, IonButton, withIonLifeCycle } from '@ionic/react';
import React from 'react';
import Phaser from 'phaser';
import { IonPhaser } from '@ion-phaser/react';

import './Home.css';

class Home extends React.Component {
	state = {
		initialize: false,
		game: {
			width: "100%",
			height: "100%",
			type: Phaser.AUTO,
			scene: {}
		}
	}

	render() {

		const { initialize, game } = this.state;

		return (
			<IonPage>
				<IonHeader>
					<IonToolbar>
						<IonTitle>Hola</IonTitle>
					</IonToolbar>
				</IonHeader>
				<IonContent>			
					<IonPhaser game={game} initialize={initialize} />
				</IonContent>
			</IonPage>
		);
	}
}

export default withIonLifeCycle(Home);

```
The error occurs when I pass the game object to the game property, I am using Ionic with react. I tried your react example but not working to. I hope that you can help me or is a mistake from my part... Is a blank project with Ionic cli, and I am new using this frameworks sorry for my english, regards.

**Comment by jdnichollsc** [comment]
Hola Luis, puedes hablar en español, tu tranqui! jaja
Estás usando TypeScript, cierto? Para corregir este error de tipos puedes hacer esto:
```
interface Props {}
interface State {
  initialize: boolean
  game: Phaser.Game
}

class Home extends React.Component<Props, State> {

}
```

Let me know 👍

**Comment by LuchitoDev** [comment]
Hola Juan David, gracias por tu ayuda y el apollo moral jajaja
disculpa tanta molestia, practicamente soy novato usando Ionic con React y TypeScript... y me esta resultando dificil implementar ion-phaser, hice lo que me recomendaste y ahora tengo otro par de detalles dejo por aqui una captura. 

<img width="1270" alt="Captura de Pantalla 2020-03-04 a la(s) 9 36 18 a  m" src="https://user-images.githubusercontent.com/19392344/75895931-ecd86300-5dfb-11ea-803a-827082c07ecb.png">

Realmente no se que pasa ahi, tambien tengo un mensaje de alerta sobre el initialize, espero puedas ayudarme, saludos.

**Comment by jdnichollsc** [comment]
No problem! Para corregir ese tipo podrías clear tu escena antes, ejemplo:
```
class MyScene extends Phaser.Scene {
  helloWorld: Phaser.GameObjects.Text

  init () {
    this.cameras.main.setBackgroundColor('#24252A');
  }

  create () {
    this.helloWorld = this.add.text(
      this.cameras.main.centerX, 
      this.cameras.main.centerY, 
      "Hello World", { 
        font: "40px Arial", 
        fill: "#ffffff" 
      }
    );
    this.helloWorld.setOrigin(0.5);
  }

  setAngle (angle: number) {
    this.helloWorld.angle = angle;
  }
}
```

y ya en el objeto game le pasas la escena: `scene: MyScene` 👍

**Comment by LuchitoDev** [comment]
Sigue sin funcionar, creando la clase extendida de Phaser.Scene o pasandole directamente el objeto con las funciones init, create, update... siempre me genera el mismo problema

**Comment by jdnichollsc** [comment]
Bueno, ya es el manejo de los tipos de Phaser, no está relacionado con IonPhaser 😅

**Comment by LuchitoDev** [comment]
Gracias David, sera que podrias orientarme de alguna otra forma. Te lo agredeceria mucho...

**Comment by jdnichollsc** [comment]
Creo que mi consejo sería practicar más sobre TypeScript :)
