### ISSUE TITLE
Must set explicit renderType in custom environment

### ISSUE THREAD

**Issue by CKGrafico** [proyecto26/ion-phaser#17]
With my config or an empty configuration I've this error:
`Must set explicit renderType in custom environment`

![image](https://user-images.githubusercontent.com/2048511/80304400-ca3c4800-87b5-11ea-9c7b-73ccc38463b2.png)

version: "@ion-phaser/react": "^1.2.1",

**Comment by jdnichollsc** [comment]
Please share the config of your game :)

**Comment by CKGrafico** [comment]
I've tried with empty config and have the same error but let me share my config.
When I debug if I change to Phaser.CANVAS this line still assumes CONST.AUTO

```
    const config = {
      type: Phaser.AUTO,
      scale: {
        mode: Phaser.Scale.FIT,
        parent: 'game',
        autoCenter: Phaser.Scale.CENTER_BOTH,
        width: '100%',
        height: '100%'
      },
      pixelArt: true,
      render: {
        antialias: false,
        pixelArt: true,
        roundPixels: true
      },
      physics: {
        default: 'arcade',
        arcade: {
          gravity: { y: 400 }
          // debug: true
        }
      },
      scene
    };
```

**Comment by jdnichollsc** [comment]
what version of Phaser are you using? thanks!

**Comment by CKGrafico** [comment]
3.22

"dependencies": {
    "@datorama/akita": "^4.19.2",
    "@ion-phaser/react": "^1.2.1",
    "bootstrap": "^4.4.1",
    "i18next": "^19.1.0",
    "inversify-hooks": "^2.0.0-alpha3",
    "node-sass": "^4.13.1",
    "normalize-scss": "^7.0.1",
    "open-simplex-noise": "^2.2.0",
    "phaser": "^3.22.0",
    "react": "^16.12.0",
    "react-bootstrap": "^1.0.0-beta.16",
    "react-dom": "^16.12.0",
    "react-i18next": "^11.3.2",
    "react-transition-group": "^4.3.0",
    "reflect-metadata": "^0.1.13",
    "svgo": "1.3.2"
  },

**Comment by jdnichollsc** [comment]
Ok, I updated the packages and your configuration is working in the demo project also with types => https://github.com/proyecto26/ion-phaser/blob/master/demo-react/src/App.tsx#L35

**Comment by CKGrafico** [comment]
After update I have this error:
```
index.js:1 TypeError: Cannot read property 'hasOwnProperty' of null
    at GetValue (ion-phaser.entry.js:3945)
```

```
  else if (key.indexOf('.') !== -1) {
        var keys = key.split('.');
        var parent = source;
        var value = defaultValue;
        //  Use for loop here so we can break early
        for (var i = 0; i < keys.length; i++) {
            if (parent.hasOwnProperty(keys[i])) {
                //  Yes it has a key property, let's carry on down
                value = parent[keys[i]];
                parent = parent[keys[i]];
            }
            else {
                //  Can't go any further, so reset to default
                value = defaultValue;
                break;
            }
        }
```

**Comment by jdnichollsc** [comment]
Please attach a demo to be able to reproduce that issue
