### ISSUE TITLE
ion-phaser dist appears to bundle Phaser

### ISSUE THREAD

**Issue by JingYenLoh** [proyecto26/ion-phaser#18]
`core/dist/esm-es5/ion-phaser.entry.js` appears to bundle Phaser in, although #7 reports a much smaller bundle size.

**Comment by jdnichollsc** [comment]
The bundle size doesn't include Phaser: https://bundlephobia.com/result?p=@ion-phaser/core@1.2.3

**Comment by JingYenLoh** [comment]
Yes, I've seen that link, but looking at the file it doesn't seem that way.

I've created a [minimal repro](https://github.com/JingYenLoh/phaser-repro) in React. This is the map it generates.

![image](https://user-images.githubusercontent.com/22059033/83955571-b4c33f00-a886-11ea-8062-326e6621bb70.png)

**Comment by jdnichollsc** [comment]
You're right, let me investigate 👍 https://unpkg.com/@ion-phaser/core@1.2.3/dist/esm-es5/ion-phaser.entry.js

**Comment by jdnichollsc** [comment]
I'm going to try with the last version of StencilJS, please stay tuned :)

**Comment by alcaitiff** [comment]
Nothing until now?

**Comment by jdnichollsc** [comment]
Let me try using last version of StencilJS :)

**Comment by jdnichollsc** [comment]
Hello folks, Do you know any good npm package to analyze bundle size locally?

**Comment by jdnichollsc** [comment]
Please let me know if the issue persist, thanks!
