### ISSUE TITLE
React demo Can't import the named export 'b' from EcmaScript module

### ISSUE THREAD

**Issue by stahlmanDesign** [proyecto26/ion-phaser#2]
I'm trying to use Phaser with React.

I installed with `npm install @ion-phaser/core --save` and `npm install @ion-phaser/react --save` and then tried to run the code in this demo:
https://github.com/proyecto26/ion-phaser/tree/master/react

I'm using create-react-app and React 16.8.6

<img width="615" alt="image" src="https://user-images.githubusercontent.com/972804/61929234-d8201c80-af48-11e9-8442-dc72719f4a33.png">

**Comment by jdnichollsc** [comment]
Hi @stahlmanDesign, thanks for reporting this issue!
Can you try installing `yarn add @ion-phaser/react` only?
Let me know please 👍

**Comment by stahlmanDesign** [comment]
I'm not using yarn, but when use `npm install @ion-phaser/react` without `@ion-phaser/core` the result is the same error.

I tried to create a codepen but `@ion-phaser/react` is not hosted at the same CDN as the core: `https://unpkg.com/@ionic/core@4.4.2/dist/ionic.js`

https://codepen.io/stahlmandesign/pen/bXBGxE?editors=1111

**Comment by jdnichollsc** [comment]
try with this https://unpkg.com/@ion-phaser/react@1.1.0/dist/index.js

**Comment by stahlmanDesign** [comment]
That doesn't seem to be the expected code. The entire contents of `https://unpkg.com/@ion-phaser/react@1.1.0/dist/index.js` are just:
```
export * from './components';
//# sourceMappingURL=index.js.map
```

**Comment by jdnichollsc** [comment]
Can you debug in the `demo-react` folder please? https://github.com/proyecto26/ion-phaser/blob/master/demo-react/package.json#L6

**Comment by jdnichollsc** [comment]
@stahlmanDesign check the `dist` folder and let me know please 👍  https://unpkg.com/browse/@ion-phaser/react@1.1.0/dist/

**Comment by jdnichollsc** [comment]
I've reported this error, I was able to reproduce this issue from **Vue.js** https://github.com/ionic-team/stencil/issues/1842

**Comment by jdnichollsc** [comment]
Try the last version 1.2.0 and let me know 👍
