### ISSUE TITLE
Pointer events shift when scrolling the canvas

### ISSUE THREAD

**Issue by aldebout** [proyecto26/ion-phaser#24]
I'm using the react package.

When I scroll the page on which the canvas is present after the game has loaded, subsequent calls to `pointer.y` get shifted by the scroll amount.

My game config:

```tsx
{
  type: Phaser.AUTO,
  scale: {
    mode: Phaser.Scale.FIT,
    autoCenter: Phaser.Scale.CENTER_BOTH,
    width: 700,
    height: 700,
  },
  scene: playGame,
}
```

My jsx:
```tsx
<IonPhaser
    style={{
      width: '350px',
      height: '350px',
    }}
    key={gameId}
    game={game}
    initialize={initialize}
  />
```

and the game is basically taken from [here](https://www.emanueleferonato.com/2019/07/08/bug-fix-match-3-bejeweled-html5-prototype-built-with-phaser-updated-to-phaser-3-adding-object-pooling-and-using-ecma-script-6-conventions-swipe-routine-fixed/).

Edit: After further testing, it's also the case without the position absolute, reflected it in my code.

**Comment by jdnichollsc** [comment]
Can you attach a GitHub repo to be able to reproduce this issue? :)

**Comment by jdnichollsc** [comment]
@aldebout please create a demo to reopen this issue, try here: https://stackblitz.com
