### ISSUE TITLE
Cannot add 2 different scenes to the game config

### ISSUE THREAD

**Issue by gilbertoalmeida** [proyecto26/ion-phaser#26]
Hi, thanks for the work on this.

I am trying out creating a game in react with ion-phaser and I am running into this problem that I cannot add 2 different scenes to the game config.

This is how App.js looks like. I notice that only the last scene in the Array (GameScene) is loaded. If I invert the order in the array, only the other one is loaded.
```
import React from 'react'
import Phaser from 'phaser'
import { IonPhaser } from '@ion-phaser/react'
import { BootScene } from "./BootScene"
import { GameScene } from "./GameScene"

function App() {
  const state = {
    initialize: true,
    game: {
      width: "100%",
      height: "100%",
      type: Phaser.AUTO,
      scene: [BootScene, GameScene]
    }
  }


  const { initialize, game } = state
  return (
    <div className="App">
      <IonPhaser game={game} initialize={initialize} />
    </div>
  );
}

export default App;
```

I tried out in a simple HTML with just pure phase and both Scenes are loaded normally. 

Here's a simple repo for reproducing:
https://github.com/gilbertoalmeida/ion-phaser-2-scenes

**Comment by jdnichollsc** [comment]
Thanks for sharing the repo, let me try ASAP :)

**Comment by gilbertoalmeida** [comment]
hi Juan, did you have a chance to look into this?

**Comment by jdnichollsc** [comment]
Sorry for the delay, try creating a config scene like this: https://github.com/proyecto26/ion-phaser/blob/develop/demo-angular/src/app/app.component.ts#L52

**Comment by jdnichollsc** [comment]
Let me know if the issue persist, thanks!
