### ISSUE TITLE
How to upgrade to Phaser 3.52.0

### ISSUE THREAD

**Issue by ccolomboext** [proyecto26/ion-phaser#27]
Right now the version of Phaser is freezed at 3.19.0 and I'm getting a lot of errors that, according to the developer, would be solved by upgrading it.

Is there any way to upgrade it?

**Comment by jdnichollsc** [comment]
Ok give me a moment to fix the issue with this peer dependency

**Comment by NilsMinor** [comment]
Hey @jdnichollsc any updates on this topic? I also would like to use phaser 3.52 but ion-phaser depends on 3.19 :)

**Comment by ccolomboext** [comment]
Hey @NilsMinor,

As a workaround I endup creating a componenet that manages Phaser's game instance. Here follows the base code for the componenet, maybe you'll have to tweak your CSS to actually show the canvas but that depends a lot on your layout. Hope it helps!

```
import React from "react";
import Phaser from "phaser";

let game = null;

class Game extends React.Component {
  constructor(props) {
    super(props);
  }

  render() {
    return (
      <div id="game-container"></div>
    );
  }

  componentDidMount() {
      game = new Phaser.Game({
        type: Phaser.AUTO,
        parent: "game-container",
        scale: {
          mode: Phaser.Scale.RESIZE,
          autoCenter: Phaser.Scale.CENTER_BOTH,
        },
        scene: [BootScene],
      });
  }

  getScene(key) {
    if (game && game.scene) {
      return game.scene.getScene(key);
    }
  }

  callFunctionInsideScene() {
    this.getScene("SomeGameSceneKey").doSomethingInsideTheScene();
  }

  componentWillUnmount() {
    game.destroy(true);
    game = null;
  }
}

```

**Comment by jdnichollsc** [comment]
Let me fix that during this weekend, is you are using React you can try using hooks: https://stackblitz.com/edit/react-ts-yz2wke?file=index.tsx

**Comment by NilsMinor** [comment]
I am using angular and it works really well :) But I have some issues with version 3.19 and I hope that these issues are fixed in a newer version. But as ion-phaser depends on 3.19 I am not able to update. Thanks for updating @jdnichollsc 👍

**Comment by NilsMinor** [comment]
Hey :) Any updates on the ion-phaser/phaser dependency ? I do not really understand how to fix this problem by myself with adding any code to the package.json for example, so I really need you to update the dependency inside ion-phaser ^^

Thanks, Nils :)

**Comment by jdnichollsc** [comment]
Let me try to do that ASAP, I need to identify what's the problem with the current configuration because Phaser is a peer dependency, very odd

**Comment by jdnichollsc** [comment]
Do you know any good npm package to analyze bundle size locally?

**Comment by NilsMinor** [comment]
I never used a nom package to analyze the size but this (https://www.npmjs.com/package/webpack-bundle-analyzer) seams to do exactly what you are looking for ? :)

**Comment by Marchiuzzz** [comment]
I am using Vue and also need Phaser version of 3.50 or higher. I am a bit confused since in package.json I do have "phaser": "^3.52.0" but none of the functions which came with 3.5 work for me

**Comment by NilsMinor** [comment]
Hey @jdnichollsc sorry for bugging you :D did you came up with a solution?
Best regards,
Nils

**Comment by jdnichollsc** [comment]
I'm trying to solve the issue with this peer dependency, any reaction or comment from the below issue itself is really appreciated! https://github.com/ionic-team/stencil/issues/2829

**Comment by jdnichollsc** [comment]
Please check the new version and let me know 👍

**Comment by jdnichollsc** [comment]
Let me know if the issue persist, thanks!
