### ISSUE TITLE
Using a custom `Phaser.Game` class

### ISSUE THREAD

**Issue by eli-s-r** [proyecto26/ion-phaser#32]
Hi! I'm having issues getting this to work with my setup which uses a custom class that extends `Phaser.Game` (necessary as there's data that needs to be passed into the game and its scenes from React). I noticed that the game is initialized by [instantiating a `new Phaser.Game` directly](https://github.com/proyecto26/ion-phaser/blob/0382047f6df5bb1b7898226ee49dcc78c69e6121/src/components/ion-phaser/ion-phaser.tsx#L86), but can't find a way to customize this. I'm also a bit confused as to the purpose of the `instance` prop on the `GameInstance` type, as instantiating the game externally doesn't allow for the necessary ref to be passed into the game. Is there any way I might be able to get around this?

Thank you so much!

**Comment by jdnichollsc** [comment]
For that specific scenario I recommend you using Phaser with React hooks instead, e.g: https://stackblitz.com/edit/react-ts-yz2wke?file=index.tsx
