### ISSUE TITLE
Property 'ion-phaser' does not exist on type 'JSX.IntrinsicElements'

### ISSUE THREAD

**Issue by AsadDUET** [proyecto26/ion-phaser#35]
This code gives error in .tsx file. what is wrong??

`import React from 'react'
import ReactDOM from 'react-dom'
import { defineCustomElements as defineIonPhaser } from '@ion-phaser/core/loader'
import Phaser from 'phaser'

const game = {
  width: "100%",
  height: "100%",
  type: Phaser.AUTO,
  scene: {}
}

ReactDOM.render(<ion-phaser ref={el => el.game = game} />, document.getElementById('root'));

defineIonPhaser(window);`

Error: Property '**ion-phaser**' does not exist on type 'JSX.IntrinsicElements'

**Comment by jdnichollsc** [comment]
Can you try using this component into another component please?

**Comment by jdnichollsc** [comment]
Nevermid, please use the package for react https://www.npmjs.com/package/@ion-phaser/react
