### ISSUE TITLE
use in Taro

### ISSUE THREAD

**Issue by Now-Sprouting** [proyecto26/ion-phaser#38]
I can’t use this plug-in in taro-react. Does this plug-in support taro-react?

**Comment by jdnichollsc** [comment]
What's that? 🤔

**Comment by Now-Sprouting** [comment]
A very popular front-end framework that can adapt to multiple ends in China --- Taro

**Comment by jdnichollsc** [comment]
Oh I can't read Chinese, sorry 😞  Any pull request is welcome! 👍
