### ISSUE TITLE
React example code needs config

### ISSUE THREAD

**Issue by gabeo14** [proyecto26/ion-phaser#4]
The sample code here: 
https://github.com/proyecto26/ion-phaser/blob/master/react/README.md 
is missing the phaser config on componentDidMount.

Adding this line:

componentDidMount() {
    new Phaser.Game(this.state.game)
  }

between the state and render function get it working. 

Great project and good work!

**Comment by gabeo14** [comment]
just realized that this doesn't solve the config error I'm getting, but does get the phaser scene to actually display with the rotating hello world.

**Comment by jdnichollsc** [comment]
> componentDidMount() {
>   new Phaser.Game(this.state.game)
> }

Nope, you don't need that, the idea with this web component is initialize the game internally as you can see here => https://github.com/proyecto26/ion-phaser/blob/master/src/components/ion-phaser/ion-phaser.tsx#L60

**Comment by gabeo14** [comment]
OK I may have done something wrong then as the example react code wouldn't load without that. I'm also receiving an error in Chrome consol saying error : game config is needed or something along those lines. I'll post the full error when I'm back at my computer and also try restarting from scratch.

**Comment by jdnichollsc** [comment]
Let me know please, it would be awesome if you can share your code 👍

**Comment by gabeo14** [comment]
https://github.com/gabeo14/ion-phaser-react-test

Here's my repo for it as it is now. Feel free to take a look. I'll try to replicate that error tomorrow when I get a chance.

**Comment by jdnichollsc** [comment]
Remember remove this `new Phaser.Game(this.state.game)`

**Comment by gabeo14** [comment]
So when I run it as localhost with that removed/ commented out I just get a white screen. When I inspect, this is what's in the body tag, along with a few script tags.

`<div id="root">
	<ion-phaser game="[object Object]" initialize="true" class="hydrated"></ion-phaser>
</div>`

When it's present though, I get the phaser stuff displaying with the dark background and rotating text in the center.

The error that I have in the chrome console, regardless of the presence of that line is as follows.

Error: The configuration of the game is required
    at IonPhaser.initializeGame (ion-phaser.entry.js:156)
    at IonPhaser.componentWillLoad (ion-phaser.entry.js:209)
    at ionphaser-c6124867.js:480
    at step (ionphaser-c6124867.js:146)
    at Object.next (ionphaser-c6124867.js:77)
    at ionphaser-c6124867.js:49
    at new Promise (<anonymous>)
    at push.../node_modules/@ion-phaser/core/dist/esm/legacy/ionphaser-c6124867.js.__awaiter (ionphaser-c6124867.js:26)
    at safeCall (ionphaser-c6124867.js:465)
    at ionphaser-c6124867.js:522
    at step (ionphaser-c6124867.js:146)
    at Object.next (ionphaser-c6124867.js:77)
    at ionphaser-c6124867.js:49
    at new Promise (<anonymous>)
    at push.../node_modules/@ion-phaser/core/dist/esm/legacy/ionphaser-c6124867.js.__awaiter (ionphaser-c6124867.js:26)
    at scheduleUpdate (ionphaser-c6124867.js:506)
    at ionphaser-c6124867.js:902
    at step (ionphaser-c6124867.js:146)
    at Object.next (ionphaser-c6124867.js:77)
    at fulfilled (ionphaser-c6124867.js:29)
console.<computed> @ index.js:1375

Not sure if the two issues are related or not. I'll start over with a new react project and fresh install of ion-phaser-react and let you know if anything changes.

**Comment by gabeo14** [comment]
Just spun up a brand new project with ion-phaser/react and had the same result. It doesn't work until I add 
`componentDidMount() {
new Phaser.Game(this.state.game)
}`

Same error present in chrome console as well.

**Comment by nagyv** [comment]
@jdnichollsc I have the same problem.

You can find my example repo at https://github.com/nagyv/ionphaser-react-demo

**Comment by jdnichollsc** [comment]
let me debug at night

**Comment by jdnichollsc** [comment]
I'm going to publish a new version, in the meantime can you download the repo and debug from `demo-react` folder? https://github.com/proyecto26/ion-phaser/blob/master/demo-react/
Please let me know

**Comment by jdnichollsc** [comment]
Try the last version 1.2.0 and let me know 👍

**Comment by gabeo14** [comment]
> Try the last version 1.2.0 and let me know 👍

Just did and it's working. Thanks!

**Comment by jdnichollsc** [comment]
Awesome, sorry for the delay!
