### ISSUE TITLE
Some functions are missing

### ISSUE THREAD

**Issue by Marchiuzzz** [proyecto26/ion-phaser#48]
I'm trying to use `setBoundsRectangle` method on Physics arcade body, which is suppose to be available since Phaser 3.20 but it seems this function is missing from this package. I get `setBoundsRectangle` is undefined. I checked the code of node_modules and indeed, everything related to `customBoundsRectangle` is missing.
This is the original Phaser https://github.com/photonstorm/phaser/blob/v3.51.0/src/physics/arcade/Body.js#L1165

![image](https://user-images.githubusercontent.com/73941456/189310100-a9c7d496-eadd-44ee-b3b0-cf1fc5d461a4.png)

And this is the code from this package
![image](https://user-images.githubusercontent.com/73941456/189310161-f36f8a7f-b68c-4919-9ea1-e3799b3aa49f.png)

Why are some functions missing even though this package is suppose to be using 3.51?

**Comment by jdnichollsc** [comment]
hello @Marchiuzzz, can you create a reproducible demo to be able to debug your issue? Phaser is a peer dependency for this package, are you using Angular, React or VueJS?

**Comment by Marchiuzzz** [comment]
@jdnichollsc I'm using Vue.js. Apparently I was using an older version of this package, updating to 1.3.0 solved this issue.

**Comment by jdnichollsc** [comment]
@Marchiuzzz thanks for letting me know! ❤️
