### ISSUE TITLE
Scene changing not working

### ISSUE THREAD

**Issue by r0m1n** [proyecto26/ion-phaser#5]
Trying to change one scene from other. After executing 

> this.scene.start("OtherScene")

 just have black screen without any errors. Any help?

```
  game = {
    width: 600,
    height: 600,
    type: Phaser.AUTO,
    scene: [OtherScene,FirstScene],
    physics: {
      default: 'arcade',
      arcade: {
        gravity: { y: 200 }
      }},
    instance: null
  }

```

```

 class FirstScene extends Phaser.Scene{

  constructor() {
    super({key: 'FirstScene'});
  }

  preload() {
...
  }

  create() {
....

    this.input.keyboard.on('keyup_S', ()=>{
      this.scene.start("OtherScene");
    }, this);

  }

class OtherScene extends Phaser.Scene{

  constructor(){
    super({key:'OtherScene'});
  
preload() {
console.log('OtherScene') //not working!!
...
  }
  }
```

**Comment by jdnichollsc** [comment]
Please share your example running from Codepen using only VanillaJS :)

**Comment by jdnichollsc** [comment]
or share the repo with your code please

**Comment by jdnichollsc** [comment]
@r0m1n what framework/library are you using? Angular, Vue or ReactJS?

**Comment by jdnichollsc** [comment]
Ok, I was able to reproduce this issue, it looks an issue from Phaser itself, after debugging different ways you can fix this by using a **BootScene**: https://github.com/proyecto26/ion-phaser/blob/master/demo-angular/src/app/app.component.ts#L52
