### ISSUE TITLE
angular demo not work

### ISSUE THREAD

**Issue by lalalalaluk** [proyecto26/ion-phaser#6]
hello,
first thx thix amazing project

I install the whole project

and go angular demo folder

after npm install  -> ng serve

i get this error 

ERROR in src/main.ts(3,57): error TS2307: Cannot find module '@ion-phaser/core/loader'.

is there any idea?

thanks you

**Comment by jdnichollsc** [comment]
Are you installing this component from your project by using `npm install @ion-phaser/core --save`?

If you want to debug this repo locally, you need to build the web component first, try these commands:
```
npm install
npm run build
cd demo-angular
npm install
npm run start
```

Let me know 👍 

Regards

**Comment by lalalalaluk** [comment]
I can run the demo-angular now~ thank you~

but i ng new a angular project

follow the tutorial and demo-angular

it still has error

````
GET http://localhost:4200/node_modules/@ion-phaser/core/dist/ionphaser.js net::ERR_ABORTED 404 (Not Found)
requestAnimationFrame.js:20 Uncaught ReferenceError: global is not defined
    at Object../node_modules/phaser/src/polyfills/requestAnimationFrame.js (requestAnimationFrame.js:20)
    at __webpack_require__ (bootstrap:84)
    at Object../node_modules/phaser/src/polyfills/index.js (index.js:7)
    at __webpack_require__ (bootstrap:84)
    at Object../node_modules/phaser/src/phaser.js (phaser.js:7)
    at __webpack_require__ (bootstrap:84)
    at Module../src/app/app.component.ts (main.js:391)
    at __webpack_require__ (bootstrap:84)
    at Module../src/app/app.module.ts (app.component.ts:71)
    at __webpack_require__ (bootstrap:84)
````

my github is here
[https://github.com/lalalalaluk/ion-phaser-test](https://github.com/lalalalaluk/ion-phaser-test)

is there anything i did wrong ?

thank you

**Comment by jdnichollsc** [comment]
mmm let me check, can you try adding this configuration from your project? https://github.com/proyecto26/ion-phaser/blob/master/demo-angular/tsconfig.json#L24

Let me know 👍

**Comment by jdnichollsc** [comment]
Ohh interesting, it looks like the issue can be fixed by using this  😄  https://stackoverflow.com/a/50723577/1532821

Check this https://github.com/proyecto26/ion-phaser/blob/master/demo-angular/src/polyfills.ts#L65

**Comment by lalalalaluk** [comment]
it works fine 
thank you soooooo much  :)
