### ISSUE TITLE
premove phaser from bundle

### ISSUE THREAD

**Issue by iKest** [proyecto26/ion-phaser#7]
please remove phaser from the distribution and use global import for it.
https://prnt.sc/pkeuw8

**Comment by jdnichollsc** [comment]
Very odd because `Phaser` is a peer dependency [here](https://github.com/proyecto26/ion-phaser/blob/master/package.json#L37), let me check 👍

**Comment by jdnichollsc** [comment]
@iKest thanks for reporting this issue, check the last version! <3 
<img width="1006" alt="Captura de Pantalla 2019-11-27 a la(s) 2 25 56 p  m" src="https://user-images.githubusercontent.com/2154886/69753624-047bbd80-1122-11ea-99ff-410bcdddc9cb.png">
